spring.application.name=civokbank


spring.datasource.url=jdbc:mysql://localhost:3306/civok_bank_db
spring.datasource.username=root
spring.datasource.password=Tata33chidi$

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql = true